trainer:
  max_epochs: 5
  limit_train_batches: 100
  limit_val_batches: 20
  precision: 16-mixed
  devices: 1
  accelerator: auto
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: logs_test
        name: fast_val
